--- scripts/dtc/include-prefixes/arm/Makefile	2024-03-23 21:12:48.453938477 +0800
+++ scripts/dtc/include-prefixes/arm/Makefile	2024-03-23 20:32:39.649779679 +0800
@@ -972,14 +972,69 @@
 	r9a06g032-rzn1d400-db.dtb \
 	sh73a0-kzm9g.dtb
 dtb-$(CONFIG_ARCH_ROCKCHIP) += \
+	rv1103g-38x38-ipc-v10.dtb \
+	rv1103g-battery-ipc-v10.dtb \
+	rv1103g-battery-ipc-v11.dtb \
+	rv1103g-evb-mcu-display-v11.dtb \
+	rv1103g-evb-v10.dtb \
+	rv1103g-evb-v11.dtb \
+	rv1103g-evb-v11-sii902x-bt6562hdmi.dtb \
+	rv1103g-evb2-v10.dtb \
+	rv1103g-rmsl311-dloc-sl-v10.dtb \
+	rv1103g-scaner-v10.dtb \
+	rv1106g-38x38-ipc-v10.dtb \
+	rv1106g-38x38-ipc-v10-spi-nand.dtb \
+	rv1106g-evb1-mcu-display-v11.dtb \
+	rv1106g-evb1-mcu-display-v20.dtb \
+	rv1106g-evb1-rgb-display-v11.dtb \
+	rv1106g-evb1-v10.dtb \
+	rv1106g-evb1-v11.dtb \
+	rv1106g-evb1-v11-4k.dtb \
+	rv1106g-evb1-v11-cvr.dtb \
+	rv1106g-evb1-v11-cvr-dual-cam.dtb \
+	rv1106g-evb1-v11-spi-nand-cvr.dtb \
+	rv1106g-evb1-v11-sii902x-bt11202hdmi.dtb \
+	rv1106g-evb1-v11-sii902x-rgb2hdmi.dtb \
+	rv1106g-evb1-v10-dual-cam.dtb \
+	rv1106g-evb1-v11-dual-cam.dtb \
+	rv1106g-evb1-v10-facial-gate.dtb \
+	rv1106g-evb1-v11-facial-gate.dtb \
+	rv1106g-evb1-v10-spi-nand.dtb \
+	rv1106g-evb1-v10-spi-nor.dtb \
+	rv1106g-evb1-v11-nofastae-spi-nand.dtb \
+	rv1106g-evb1-v11-cvr-ext-dual-cam.dtb \
+	rv1106g-evb2-v10.dtb \
+	rv1106g-evb2-v10-dual-camera.dtb \
+	rv1106g-evb2-v11-emmc.dtb \
+	rv1106g-evb2-v11-trailcam-emmc.dtb \
+	rv1106g-evb2-v12-aov-spi-nor.dtb \
+	rv1106g-evb2-v12-dual-camera-avs.dtb \
+	rv1106g-evb2-v12-nofastae-emmc.dtb \
+	rv1106g-evb2-v12-nofastae-spi-nand.dtb \
+	rv1106g-evb2-v12-nofastae-spi-nor.dtb \
+	rv1106g-evb2-v12-wakeup.dtb \
+	rv1106g-smart-door-lock-rmsl-v10.dtb \
+	rv1106g-smart-door-lock-rmsl-v12.dtb \
+	rv1106g-uvc-demo-v10.dtb \
+	rv1106g-uvc-demo-v10-spi-nor.dtb \
 	rv1108-elgin-r1.dtb \
 	rv1108-evb.dtb \
+	rv1126-evb-ddr3-v10.dtb \
+	rv1126-evb-ddr3-v12.dtb \
+	rv1126-evb-ddr3-v12-spi-nand.dtb \
+	rv1126-evb-ddr3-v12-spi-nor.dtb \
+	rv1126-evb-ddr3-v13.dtb \
 	rk3036-evb.dtb \
+	rk3036-evb1-ddr3-v10.dtb \
 	rk3036-kylin.dtb \
 	rk3066a-bqcurie2.dtb \
 	rk3066a-marsboard.dtb \
 	rk3066a-mk808.dtb \
 	rk3066a-rayeager.dtb \
+	rk3126c-evb-ddr3-v10-linux.dtb \
+	rk3126c-evb-ddr3-v10-linux-slc.dtb \
+	rk3128-evb-ddr3-v10-linux.dtb \
+	rk3128-evb-ddr3-v10-linux-spi-nand.dtb \
 	rk3188-bqedison2qc.dtb \
 	rk3188-px3-evb.dtb \
 	rk3188-radxarock.dtb \
@@ -1009,7 +1064,12 @@
 	rk3288-veyron-pinky.dtb \
 	rk3288-veyron-speedy.dtb \
 	rk3288-veyron-tiger.dtb \
-	rk3288-vyasa.dtb
+	rk3288-vyasa.dtb \
+	rk3308-evb-audio-v10-display-rgb-aarch32.dtb \
+	rk3308bs-evb-amic-v11-aarch32.dtb \
+	rk3308bs-evb-dmic-pdm-v11-aarch32.dtb \
+	rk3308bs-evb-mipi-display-v11-aarch32.dtb \
+	rk3308hs-voice-module-board-v10-aarch32.dtb
 dtb-$(CONFIG_ARCH_S3C24XX) += \
 	s3c2416-smdk2416.dtb
 dtb-$(CONFIG_ARCH_S3C64XX) += \
